### ISSUE TITLE
Can't resolve '@material-ui/lab/Slider' error

### ISSUE THREAD

**Issue by ajitgoel** [alexanmtz/material-sense#12] opened 2019-10-04 00:34 UTC
I am getting the following error after running `npm install` and running `yarn start `in the application. What am I missing?

Failed to compile
./src/components/Dashboard.js
Module not found: Can't resolve '@material-ui/lab/Slider' in 'C:\temp\material-sense-master\src\components'

**Comment by alexanmtz** [comment] 2019-10-04 11:39
Thanks @ajitgoel to report this bug, I just merged a fix for this at: #13 , please pull the latest changes from master and try again and let me know if the slider will work properly.

**Comment by helios-ag** [comment] 2019-10-19 05:42
Well it's not a bug, because project deps was installed through npm, and npm ignores yarn's lock file. And now if you install project via yarn, it's broken (because of outdated lock file).
Possible solution would be to upgrade yarn's lock file, and may be add npm's lock file too.

**Closed** 2019-10-26 11:18 UTC
Labels: bug
